# Generated by Django 5.2.5 on 2025-10-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replica',
            options={'verbose_name': 'Réplica', 'verbose_name_plural': 'Réplicas'},
        ),
    ]
