# Generated by Django 5.2.5 on 2025-10-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_alter_replica_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replica',
        ),
    ]
